trigger:
  branches:
    include:
      - main  # Trigger pipeline when changes are made to the main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'Free Trial(4680f1aa-5b51-443e-b72c-8b0326165036)'  # Name of the Azure service connection
  appName: 'Demo2711'  # Azure App Service name
  resourceGroup: 'DefaultResourceGroup-CCAN'  # Azure resource group
  slotName: 'production'  # Azure slot name
  imageName: 'kk2467/python:3.13'  # Docker image name

stages:
  - stage: Deploy
    displayName: 'Deploy Docker Image to Azure'
    jobs:
      - job: Deploy
        displayName: 'Deploy Docker Container'
        steps:
          # Use AzureWebAppContainer task to deploy to Azure App Service
          - task: AzureWebAppContainer@1
            displayName: 'Deploy Docker Image to Azure App Service'
            inputs:
              azureSubscription: $(azureSubscription)  # Use the service connection
              appName: $(appName)
              resourceGroupName: $(resourceGroup)
              slotName: $(slotName)
              containerRegistry: 'docker.io'  # Use Docker Hub or Azure Container Registry
              imageName: $(imageName)
              isPush: true  # Push the image to Azure App Service
