trigger:
  branches:
    include:
      - main  # Trigger pipeline when changes are made to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use the default hosted Ubuntu agent pool

variables:
  azureSubscription: 'Free Trial(4680f1aa-5b51-443e-b72c-8b0326165036)'  # Azure service connection name
  appName: 'DemoApp'  # Azure App Service name
  resourceGroup: 'DefaultResourceGroup-CCAN'  # Azure resource group
  slotName: 'production'  # Azure slot name
  imageName: 'docker.io/kk2467/python:3.13'  # Docker image name

stages:
  - stage: Deploy
    displayName: 'Deploy Docker Image to Azure'
    jobs:
      - job: Deploy
        displayName: 'Deploy Docker Container'
        steps:
          # Step 1: Checkout code
          - checkout: self
            fetchDepth: 0  # Fetch the full history of commits (use 1 for shallow clone)
            displayName: 'Checkout code from repository'

          # Step 2: Verify and display all variables (for debugging purposes)
          - script: |
              echo "Verifying all pipeline variables..."
              echo "azureSubscription: $(azureSubscription)"
              echo "appName: $(appName)"
              echo "resourceGroup: $(resourceGroup)"
              echo "slotName: $(slotName)"
              echo "imageName: $(imageName)"
            displayName: 'Display Variables for Debugging'

          # Step 3: Deploy Docker image to Azure App Service
          - task: AzureWebAppContainer@1
            displayName: 'Deploy Docker Image to Azure App Service'
            inputs:
              azureSubscription: $(azureSubscription)  # Azure service connection name
              appName: $(appName)
              resourceGroupName: $(resourceGroup)
              slotName: $(slotName)
              containerRegistry: 'docker.io'  # Docker Hub registry
              imageName: $(imageName)  # Docker image to deploy
              isPush: false  # No push to the registry, just deploying
