trigger:
  branches:
    include:
      - main  # Trigger pipeline when changes are made to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use the default hosted Ubuntu agent pool

variables:
  azureSubscription: 'Free Trial(4680f1aa-5b51-443e-b72c-8b0326165036)'  # Azure service connection
  appName: 'Demo2711'  # Azure App Service name
  resourceGroup: 'DefaultResourceGroup-CCAN'  # Azure resource group
  slotName: 'production'  # Azure App Service slot name
  imageName: 'kk2467/python:3.13'  # Docker image name
  dockerRegistryServiceConnection: 'kk2467'

stages:
  - stage: BuildAndDeploy
    displayName: 'Build Docker Image and Deploy to Azure'
    jobs:
      - job: BuildAndDeploy
        displayName: 'Build Docker Image and Deploy'
        steps:
          # Step 1: Checkout code
          - task: Checkout@1
            displayName: 'Checkout Code'

          # Step 2: Build the Docker image
          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)  # Docker registry connection
              repository: $(imageName)  # Docker image repository
              command: 'build'
              Dockerfile: $(Build.SourcesDirectory)/Dockerfile  # Path to the Dockerfile in your repository
              tags: 'latest'

          # Step 3: Push the Docker image to Docker Hub (or Azure Container Registry)
          - task: Docker@2
            displayName: 'Push Docker Image'
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)  # Docker registry connection
              repository: $(imageName)  # Docker image repository
              command: 'push'
              tags: 'latest'

          # Step 4: Deploy Docker image to Azure App Service
          - task: AzureWebAppContainer@1
            displayName: 'Deploy Docker Image to Azure App Service'
            inputs:
              azureSubscription: $(azureSubscription)  # Azure service connection
              appName: $(appName)
              resourceGroupName: $(resourceGroup)
              slotName: $(slotName)
              containerRegistry: 'docker.io'  # Docker Hub registry
              imageName: $(imageName):latest  # The image to deploy (tagged as latest)
              isPush: true  # Push the image to Azure App Service
