trigger:
  branches:
    include:
      - main  # Trigger the pipeline when there are changes to the main branch.

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'mydockerusername/my-app'  # Use your Docker Hub or ACR image name.
  dockerRegistryServiceConnection: 'kk2467'  # Replace with your Docker registry connection name.

stages:
  - stage: Build
    displayName: 'Build and Dockerize'
    jobs:
      - job: Build
        displayName: 'Build Docker Image'
        steps:
          - task: Checkout@1  # Checkout task with version 1
            displayName: 'Checkout Code'

          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)  # Docker registry connection
              repository: $(imageName)
              command: 'build'
              Dockerfile: $(Build.SourcesDirectory)/Dockerfile
              tags: 'latest'

          - task: Docker@2
            displayName: 'Push Docker Image'
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: $(imageName)
              command: 'push'
              tags: 'latest'

  - stage: Deploy
    displayName: 'Deploy to Azure App Service'
    jobs:
      - job: Deploy
        displayName: 'Deploy Docker Container to Azure App Service'
        steps:
          - task: AzureWebAppContainer@1  # Use version 2 instead of version 1
            displayName: 'Deploy Docker Image to Azure'
            inputs:
              azureSubscription: 'Free Trial(4680f1aa-5b51-443e-b72c-8b0326165036)'  # Azure subscription service connection
              appName: 'Demo2711'  # Name of the Azure App Service
              resourceGroupName: 'DefaultResourceGroup-CCAN'  # Resource group name
              slotName: 'production'  # Deployment slot name
              containerRegistry: 'https://hub.docker.com/repositories/kk2467'  # Container registry URL (Docker Hub)
              imageName: 'mydockerusername/my-app:latest'  # Full Docker image name
              isPush: true  # Push the Docker image to Azure App Service
