trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'kk2467/python'
  dockerRegistryServiceConnection: 'kk2467'
  azureSubscription: 'Free Trial(4680f1aa-5b51-443e-b72c-8b0326165036)'
  appName: 'Demo2711'
  resourceGroup: 'DefaultResourceGroup-CCAN'
  slotName: 'production'

stages:
  - stage: Build
    displayName: 'Build and Dockerize'
    jobs:
      - job: Build
        displayName: 'Build Docker Image'
        steps:
          - task: Checkout@1
            displayName: 'Checkout Code'

          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: $(imageName)
              command: 'build'
              Dockerfile: $(Build.SourcesDirectory)/Dockerfile
              tags: 'latest'

          - task: Docker@2
            displayName: 'Push Docker Image'
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: $(imageName)
              command: 'push'
              tags: 'latest'

  - stage: Deploy
    displayName: 'Deploy to Azure App Service'
    jobs:
      - job: Deploy
        displayName: 'Deploy Docker Container to Azure App Service'
        steps:
          - task: AzureWebAppContainer@1
            displayName: 'Deploy Docker Image to Azure'
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(appName)
              resourceGroupName: $(resourceGroup)
              slotName: $(slotName)
              containerRegistry: 'docker.io'
              imageName: $(imageName):latest
              isPush: true

# Optionally, you can control how many jobs run in parallel under `jobs` or `stages`:
# This limits jobs under a stage to run concurrently (max 1 job at a time).
jobs:
  - job: Build
    displayName: 'Build Docker Image'
    maxParallel: 1  # This limits the concurrency of jobs to 1

