trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerImageName: 'azure-app'

steps:
  # Step 1: Checkout code
  - task: Checkout@1

  # Step 2: Build Docker Image
  - script: |
      docker build -t $(dockerImageName):$(Build.BuildId) .
    displayName: 'Build Docker Image'

  # Step 3: Push Docker Image to Azure App Service
  - task: AzureWebAppContainer@1
    inputs:
      azureSubscription: '<Free Trial(4680f1aa-5b51-443e-b72c-8b0326165036)>'
      appName: '<DemoLTI>'
      imageName: '$(dockerImageName):$(Build.BuildId)'
      tag: 'latest'

