trigger:
  branches:
    include:
      - main  # Adjust the branch if you want to trigger for a different branch

pool:
  vmImage: 'ubuntu-latest'  # You can use 'windows-latest' if you prefer to run on a Windows agent

variables:
  # Define any variables you'd like to use in the pipeline
  buildConfiguration: 'Release'

resources:
  repositories:
    - repository: githubRepo
      type: github
      name: 'Keshav2kumar / Azure-web-app'  # Replace with your GitHub username/repository
      endpoint: 'github.com_DemoLTI'  # The service connection name for GitHub you created earlier

steps:
  # Step 1: Checkout code from GitHub
  - checkout: githubRepo  # This step checks out the code from GitHub
  
  # Step 2: Install dependencies (if needed, e.g., for Node.js)
  - script: |
      echo Installing dependencies...
      npm install  # Assuming it's a Node.js app, change if using other frameworks
    displayName: 'Install Dependencies'

  # Step 3: Build the code (customize this to your technology stack)
  - script: |
      echo Building the code...
      npm run build  # Change this to whatever build command your project needs
    displayName: 'Build Code'

