trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerImageName: 'azure-app'

steps:
  # Step 1: Checkout code
  - task: Checkout@1

  # Step 2: Build Docker Image
  - script: |
      docker build -t $(dockerImageName):$(Build.BuildId) .C:\Users\hp\Azure demo\Azure-web-app\Azure-web-app 
    displayName: 'Build Docker Image'

  # Step 3: Push Docker Image to Azure App Service
  - task: AzureWebAppContainer@1
    inputs:
      azureSubscription: 'DemoLTI'
      appName: 'DemoLTI'
      imageName: '$(dockerImageName):$(Build.BuildId)'
      tag: 'latest'

