trigger:
  branches:
    include:
      - main  # Trigger pipeline when changes are made to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use a Microsoft-hosted Ubuntu agent

variables:
  azureSubscription: 'Free Trial(4680f1aa-5b51-443e-b72c-8b0326165036)'  # Azure service connection name
  appName: 'DemoApp'  # Azure App Service name
  resourceGroup: 'DefaultResourceGroup-CCAN'  # Azure resource group
  slotName: 'production'  # Azure slot name
  imageName: 'kk2467/python:3.13'  # Docker image name

stages:
  - stage: VerifyVariables
    displayName: 'Verify Variables'
    jobs:
      - job: VerifyVariablesJob
        displayName: 'Verify and Display Variables'
        steps:
          - script: |
              echo "Verifying all pipeline variables..."
              echo "azureSubscription: $(azureSubscription)"
              echo "appName: $(appName)"
              echo "resourceGroup: $(resourceGroup)"
              echo "slotName: $(slotName)"
              echo "imageName: $(imageName)"
            displayName: 'Display Variables for Debugging'

